<a href="https://colab.research.google.com/github/abhishekanand04/Python-Libraries/blob/feature/Oct24_Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2024-10-25 15:43:01--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 173.194.193.102, 173.194.193.101, 173.194.193.138, ...
Connecting to drive.google.com (drive.google.com)|173.194.193.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2024-10-25 15:43:01--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 74.125.69.132, 2607:f8b0:4001:c2f::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|74.125.69.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.001s

2024-10-25 15:43:03 (83.0 MB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('mckinsey.csv')
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
new_row = {'country': 'India', 'year': 2000,'population':13500000, 'continent': "Asia", 'life_exp':37.08, 'gdp_cap':900.23}
new_row

{'country': 'India',
 'year': 2000,
 'population': 13500000,
 'continent': 'Asia',
 'life_exp': 37.08,
 'gdp_cap': 900.23}

In [ ]:
pd.DataFrame([new_row])

       0     1         2     3      4       5
0  India  2000  13500000  Asia  37.08  900.23

In [ ]:
row0 = pd.DataFrame([new_row])

In [ ]:
pd.concat([df, row0])

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
0           India  2000    13500000      Asia    37.080  900.230000

[1705 rows x 6 columns]

In [ ]:
pd.concat([df, row0], ignore_index=True)

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2000    13500000      Asia    37.080  900.230000

[1705 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.loc[0]

# df.loc[0] = new row

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 0, dtype: object

In [ ]:
new_row = ['India', 2000, 13500000, 'Asia', 37.08, 900.23]
new_row

['India', 2000, 13500000, 'Asia', 37.08, 900.23]

In [ ]:
len(df.index)

1704

In [ ]:
df.loc[len(df.index)] = new_row
df.tail()

       country  year  population continent  life_exp     gdp_cap
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2000    13500000      Asia    37.080  900.230000

In [ ]:
df.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704],
      dtype='int64', length=1705)

In [ ]:
new_row2 = ['India', 2000, 13500000, 'Asia', 37.08]
new_row2

['India', 2000, 13500000, 'Asia', 37.08]

In [ ]:
df.loc[len(df.index)] = new_row2
df.tail()

ValueError: cannot set a row with mismatched columns

In [ ]:
df.iloc[len(df.index) - 1]

country          India
year              2000
population    13500000
continent         Asia
life_exp         37.08
gdp_cap         900.23
Name: 1704, dtype: object

In [ ]:
df.iloc[len(df.index)] = new_row

IndexError: iloc cannot enlarge its target object

In [ ]:
# iloc can update a row but cannot insert a new row.
df.iloc[len(df.index)-1] = ['Japan', 1000, 1350000, 'Asia', 37.08, 100.23]
df.tail()

       country  year  population continent  life_exp     gdp_cap
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     Japan  1000     1350000      Asia    37.080  100.230000

In [ ]:
# df.drop(explicit_index, axis=0) -> to delete a row
df = df.drop(3, axis=0)
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360

In [ ]:
df = df.drop(3, axis=0)
df.head()

KeyError: '[3] not found in axis'

In [ ]:
# df.index[inplicit_index] -> explicit_idex
df.index[3]

4

In [ ]:
# df.drop(list of explicit_index, axis=0) -> to delete a multiple rows
df.drop([1, 2, 4], axis=0) # drops rows with labels 1, 2, 4

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
5     Afghanistan  1977    14880372      Asia    38.438  786.113360
6     Afghanistan  1982    12881816      Asia    39.854  978.011439
7     Afghanistan  1987    13867957      Asia    40.822  852.395945
8     Afghanistan  1992    16317921      Asia    41.674  649.341395
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        Japan  1000     1350000      Asia    37.080  100.230000

[1701 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
5     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        Japan  1000     1350000      Asia    37.080  100.230000

[1704 rows x 6 columns]

In [ ]:
# df.reset_index(___) -> Reset index back to 0 -> len()-1
df.reset_index(drop=True, inplace=True)

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1700     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1701     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1702     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703        Japan  1000     1350000      Asia    37.080  100.230000

[1704 rows x 6 columns]

In [ ]:
df.reset_index()

      index      country  year  population continent  life_exp     gdp_cap
0         0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1         1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2         2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3         3  Afghanistan  1972    13079460      Asia    36.088  739.981106
4         4  Afghanistan  1977    14880372      Asia    38.438  786.113360
...     ...          ...   ...         ...       ...       ...         ...
1699   1699     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1700   1700     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1701   1701     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1702   1702     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703   1703        Japan  1000     1350000      Asia    37.080  100.230000

[1704 rows x 7 columns]

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1972    13079460      Asia    36.088  739.981106
4  Afghanistan  1977    14880372      Asia    38.438  786.113360

In [ ]:
df.loc[len(df.index)] = ['India', 2000, 13500000, 'Asia', 37.08, 900.23]
df.loc[len(df.index)] = ['Sri Lanka',2022 ,130000000, 'Asia', 80.00,500.00]
df.loc[len(df.index)] = ['Sri Lanka',2022 ,130000000, 'Asia', 80.00,500.00]
df.loc[len(df.index)] = ['India',2000 ,13500000, 'Asia', 80.00,900.23]
df.tail()

        country  year  population continent  life_exp  gdp_cap
1703      Japan  1000     1350000      Asia     37.08   100.23
1704      India  2000    13500000      Asia     37.08   900.23
1705  Sri Lanka  2022   130000000      Asia     80.00   500.00
1706  Sri Lanka  2022   130000000      Asia     80.00   500.00
1707      India  2000    13500000      Asia     80.00   900.23

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1703    False
1704    False
1705    False
1706     True
1707    False
Length: 1708, dtype: bool

In [ ]:
# Extracting duplicate rows

df.loc[df.duplicated()]

        country  year  population continent  life_exp  gdp_cap
1706  Sri Lanka  2022   130000000      Asia      80.0    500.0

In [ ]:
df.drop_duplicates()  # Deletes duplicate data

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1702     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703        Japan  1000     1350000      Asia    37.080  100.230000
1704        India  2000    13500000      Asia    37.080  900.230000
1705    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707        India  2000    13500000      Asia    80.000  900.230000

[1707 rows x 6 columns]

In [ ]:
df.drop_duplicates(keep='first')

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1702     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703        Japan  1000     1350000      Asia    37.080  100.230000
1704        India  2000    13500000      Asia    37.080  900.230000
1705    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707        India  2000    13500000      Asia    80.000  900.230000

[1707 rows x 6 columns]

In [ ]:
df.drop_duplicates(keep='last')

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1702     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703        Japan  1000     1350000      Asia    37.080  100.230000
1704        India  2000    13500000      Asia    37.080  900.230000
1706    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707        India  2000    13500000      Asia    80.000  900.230000

[1707 rows x 6 columns]

In [ ]:
df.drop_duplicates(keep=False)  # Remove all duplicates without keeping any row

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1701     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1702     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703        Japan  1000     1350000      Asia    37.080  100.230000
1704        India  2000    13500000      Asia    37.080  900.230000
1707        India  2000    13500000      Asia    80.000  900.230000

[1706 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1708 entries, 0 to 1707
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1708 non-null   object
 1   year        1708 non-null   int64
 2   population  1708 non-null   int64
 3   continent   1708 non-null   object
 4   life_exp    1708 non-null   float64
 5   gdp_cap     1708 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 93.4+ KB

In [ ]:
data = {'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
        'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
        'C': ['small', 'large', 'large', 'small', 'small', 'large', 'large', 'small'],
        'D': [1, 2, 2, 3, 3, 4, 5, 6]}

df_q = pd.DataFrame(data)

df_q
# print(sum(df.duplicated(subset=['A', 'B'])))

     A      B      C  D
0  foo    one  small  1
1  bar    one  large  2
2  foo    two  large  2
3  bar  three  small  3
4  foo    two  small  3
5  bar    two  large  4
6  foo    one  large  5
7  foo  three  small  6

In [ ]:
df_q.duplicated(subset=['A', 'B'])

0    False
1    False
2    False
3    False
4     True
5    False
6     True
7    False
dtype: bool

In [ ]:
print(sum(df_q.duplicated(subset=['A', 'B'])))

2

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1703        Japan  1000     1350000      Asia    37.080  100.230000
1704        India  2000    13500000      Asia    37.080  900.230000
1705    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1706    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707        India  2000    13500000      Asia    80.000  900.230000

[1708 rows x 6 columns]

In [ ]:
df.iloc[0:4, 0:3]

       country  year  population
0  Afghanistan  1952     8425333
1  Afghanistan  1957     9240934
2  Afghanistan  1962    10267083
3  Afghanistan  1972    13079460

In [ ]:
df.loc[0:4, 0:3]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [ ]:
cols = ["country", "population"]
df.loc[1:5, cols]

       country  population
1  Afghanistan     9240934
2  Afghanistan    10267083
3  Afghanistan    13079460
4  Afghanistan    14880372
5  Afghanistan    12881816

In [ ]:
le = df['life_exp']
le

0       28.801
1       30.332
2       31.997
3       36.088
4       38.438
         ...
1703    37.080
1704    37.080
1705    80.000
1706    80.000
1707    80.000
Name: life_exp, Length: 1708, dtype: float64

In [ ]:
le.sum()

101624.58468

In [ ]:
le.mean()

59.499171358313816

In [ ]:
le.min()

23.599

In [ ]:
df.sum()

country       AfghanistanAfghanistanAfghanistanAfghanistanAf...
year                                                    3380145
population                                          50717277835
continent     AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaEu...
life_exp                                           101624.58468
gdp_cap                                         12296981.839247
dtype: object

In [ ]:
df.mean()

TypeError: Could not convert ["AfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAfghanistanAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAngolaAngolaAngolaAngolaAngolaAngolaAngolaAngolaAngolaAngolaAngolaAngolaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaArgentinaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustraliaAustriaAustriaAustriaAustriaAustriaAustriaAustriaAustriaAustriaAustriaAustriaAustriaBahrainBahrainBahrainBahrainBahrainBahrainBahrainBahrainBahrainBahrainBahrainBahrainBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBangladeshBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBelgiumBeninBeninBeninBeninBeninBeninBeninBeninBeninBeninBeninBeninBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBoliviaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBosnia and HerzegovinaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBotswanaBrazilBrazilBrazilBrazilBrazilBrazilBrazilBrazilBrazilBrazilBrazilBrazilBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBulgariaBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurkina FasoBurundiBurundiBurundiBurundiBurundiBurundiBurundiBurundiBurundiBurundiBurundiBurundiCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCambodiaCameroonCameroonCameroonCameroonCameroonCameroonCameroonCameroonCameroonCameroonCameroonCameroonCanadaCanadaCanadaCanadaCanadaCanadaCanadaCanadaCanadaCanadaCanadaCanadaCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicCentral African RepublicChadChadChadChadChadChadChadChadChadChadChadChadChileChileChileChileChileChileChileChileChileChileChileChileChinaChinaChinaChinaChinaChinaChinaChinaChinaChinaChinaChinaColombiaColombiaColombiaColombiaColombiaColombiaColombiaColombiaColombiaColombiaColombiaColombiaComorosComorosComorosComorosComorosComorosComorosComorosComorosComorosComorosComorosCongo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Dem. Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Congo, Rep.Costa RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCosta RicaCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCote d'IvoireCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCroatiaCubaCubaCubaCubaCubaCubaCubaCubaCubaCubaCubaCubaCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicCzech RepublicDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDenmarkDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicDominican RepublicEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEcuadorEgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEl SalvadorEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEquatorial GuineaEritreaEritreaEritreaEritreaEritreaEritreaEritreaEritreaEritreaEritreaEritreaEritreaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiopiaFinlandFinlandFinlandFinlandFinlandFinlandFinlandFinlandFinlandFinlandFinlandFinlandFranceFranceFranceFranceFranceFranceFranceFranceFranceFranceFranceFranceGabonGabonGabonGabonGabonGabonGabonGabonGabonGabonGabonGabonGambiaGambiaGambiaGambiaGambiaGambiaGambiaGambiaGambiaGambiaGambiaGambiaGermanyGermanyGermanyGermanyGermanyGermanyGermanyGermanyGermanyGermanyGermanyGermanyGhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaGreeceGreeceGreeceGreeceGreeceGreeceGreeceGreeceGreeceGreeceGreeceGreeceGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuatemalaGuineaGuineaGuineaGuineaGuineaGuineaGuineaGuineaGuineaGuineaGuineaGuineaGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauGuinea-BissauHaitiHaitiHaitiHaitiHaitiHaitiHaitiHaitiHaitiHaitiHaitiHaitiHondurasHondurasHondurasHondurasHondurasHondurasHondurasHondurasHondurasHondurasHondurasHondurasHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHong Kong, ChinaHungaryHungaryHungaryHungaryHungaryHungaryHungaryHungaryHungaryHungaryHungaryHungaryIcelandIcelandIcelandIcelandIcelandIcelandIcelandIcelandIcelandIcelandIcelandIcelandIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIndonesiaIranIranIranIranIranIranIranIranIranIranIranIranIraqIraqIraqIraqIraqIraqIraqIraqIraqIraqIraqIraqIrelandIrelandIrelandIrelandIrelandIrelandIrelandIrelandIrelandIrelandIrelandIrelandIsraelIsraelIsraelIsraelIsraelIsraelIsraelIsraelIsraelIsraelIsraelIsraelItalyItalyItalyItalyItalyItalyItalyItalyItalyItalyItalyItalyJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJamaicaJapanJapanJapanJapanJapanJapanJapanJapanJapanJapanJapanJapanJordanJordanJordanJordanJordanJordanJordanJordanJordanJordanJordanJordanKenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaKorea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Dem. Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.Korea, Rep.KuwaitKuwaitKuwaitKuwaitKuwaitKuwaitKuwaitKuwaitKuwaitKuwaitKuwaitKuwaitLebanonLebanonLebanonLebanonLebanonLebanonLebanonLebanonLebanonLebanonLebanonLebanonLesothoLesothoLesothoLesothoLesothoLesothoLesothoLesothoLesothoLesothoLesothoLesothoLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLibyaLibyaLibyaLibyaLibyaLibyaLibyaLibyaLibyaLibyaLibyaLibyaMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMadagascarMalawiMalawiMalawiMalawiMalawiMalawiMalawiMalawiMalawiMalawiMalawiMalawiMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMalaysiaMaliMaliMaliMaliMaliMaliMaliMaliMaliMaliMaliMaliMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritaniaMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMauritiusMexicoMexicoMexicoMexicoMexicoMexicoMexicoMexicoMexicoMexicoMexicoMexicoMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMongoliaMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMontenegroMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMozambiqueMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarMyanmarNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNepalNepalNepalNepalNepalNepalNepalNepalNepalNepalNepalNepalNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNetherlandsNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNew ZealandNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNicaraguaNigerNigerNigerNigerNigerNigerNigerNigerNigerNigerNigerNigerNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNorwayNorwayNorwayNorwayNorwayNorwayNorwayNorwayNorwayNorwayNorwayNorwayOmanOmanOmanOmanOmanOmanOmanOmanOmanOmanOmanOmanPakistanPakistanPakistanPakistanPakistanPakistanPakistanPakistanPakistanPakistanPakistanPakistanPanamaPanamaPanamaPanamaPanamaPanamaPanamaPanamaPanamaPanamaPanamaPanamaParaguayParaguayParaguayParaguayParaguayParaguayParaguayParaguayParaguayParaguayParaguayParaguayPeruPeruPeruPeruPeruPeruPeruPeruPeruPeruPeruPeruPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPhilippinesPolandPolandPolandPolandPolandPolandPolandPolandPolandPolandPolandPolandPortugalPortugalPortugalPortugalPortugalPortugalPortugalPortugalPortugalPortugalPortugalPortugalPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoPuerto RicoReunionReunionReunionReunionReunionReunionReunionReunionReunionReunionReunionReunionRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRomaniaRwandaRwandaRwandaRwandaRwandaRwandaRwandaRwandaRwandaRwandaRwandaRwandaSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSao Tome and PrincipeSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSaudi ArabiaSenegalSenegalSenegalSenegalSenegalSenegalSenegalSenegalSenegalSenegalSenegalSenegalSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSerbiaSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSierra LeoneSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSingaporeSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSlovak RepublicSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSloveniaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSomaliaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSouth AfricaSpainSpainSpainSpainSpainSpainSpainSpainSpainSpainSpainSpainSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSri LankaSudanSudanSudanSudanSudanSudanSudanSudanSudanSudanSudanSudanSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwazilandSwedenSwedenSwedenSwedenSwedenSwedenSwedenSwedenSwedenSwedenSwedenSwedenSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSwitzerlandSyriaSyriaSyriaSyriaSyriaSyriaSyriaSyriaSyriaSyriaSyriaSyriaTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTaiwanTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaTanzaniaThailandThailandThailandThailandThailandThailandThailandThailandThailandThailandThailandThailandTogoTogoTogoTogoTogoTogoTogoTogoTogoTogoTogoTogoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTrinidad and TobagoTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyTurkeyUgandaUgandaUgandaUgandaUgandaUgandaUgandaUgandaUgandaUgandaUgandaUgandaUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited KingdomUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUnited StatesUruguayUruguayUruguayUruguayUruguayUruguayUruguayUruguayUruguayUruguayUruguayUruguayVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVenezuelaVietnamVietnamVietnamVietnamVietnamVietnamVietnamVietnamVietnamVietnamVietnamVietnamWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaWest Bank and GazaYemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.Yemen, Rep.ZambiaZambiaZambiaZambiaZambiaZambiaZambiaZambiaZambiaZambiaZambiaZambiaZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweZimbabweJapanIndiaSri LankaSri LankaIndia"] to numeric

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1972    13079460      Asia    36.088  739.981106
4     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1703        Japan  1000     1350000      Asia    37.080  100.230000
1704        India  2000    13500000      Asia    37.080  900.230000
1705    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1706    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707        India  2000    13500000      Asia    80.000  900.230000

[1708 rows x 6 columns]

In [ ]:
df.sort_values(['life_exp'])

               country  year  population continent  life_exp       gdp_cap
1291            Rwanda  1992     7290203    Africa    23.599    737.068595
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
551             Gambia  1952      284320    Africa    30.000    485.230659
35              Angola  1952     4232095    Africa    30.015   3520.610273
1343      Sierra Leone  1952     2143249    Africa    30.331    879.787736
...                ...   ...         ...       ...       ...           ...
1486       Switzerland  2007     7554661    Europe    81.701  37506.419070
694            Iceland  2007      301931    Europe    81.757  36180.789190
801              Japan  2002   127065841      Asia    82.000  28604.591900
670   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
802              Japan  2007   127467972      Asia    82.603  31656.068060

[1708 rows x 6 columns]

In [ ]:
df.sort_values(['life_exp'], ascending=False)

               country  year  population continent  life_exp       gdp_cap
802              Japan  2007   127467972      Asia    82.603  31656.068060
670   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
801              Japan  2002   127065841      Asia    82.000  28604.591900
694            Iceland  2007      301931    Europe    81.757  36180.789190
1486       Switzerland  2007     7554661    Europe    81.701  37506.419070
...                ...   ...         ...       ...       ...           ...
1343      Sierra Leone  1952     2143249    Africa    30.331    879.787736
35              Angola  1952     4232095    Africa    30.015   3520.610273
551             Gambia  1952      284320    Africa    30.000    485.230659
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
1291            Rwanda  1992     7290203    Africa    23.599    737.068595

[1708 rows x 6 columns]

In [ ]:
df.sort_values(['year', 'life_exp'])

               country  year  population continent  life_exp       gdp_cap
1703             Japan  1000     1350000      Asia    37.080    100.230000
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
551             Gambia  1952      284320    Africa    30.000    485.230659
35              Angola  1952     4232095    Africa    30.015   3520.610273
1343      Sierra Leone  1952     2143249    Africa    30.331    879.787736
...                ...   ...         ...       ...       ...           ...
694            Iceland  2007      301931    Europe    81.757  36180.789190
670   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
802              Japan  2007   127467972      Asia    82.603  31656.068060
1705         Sri Lanka  2022   130000000      Asia    80.000    500.000000
1706         Sri Lanka  2022   130000000      Asia    80.000    500.000000

[1708 rows x 6 columns]

In [ ]:
df.sort_values(['year', 'life_exp'], ascending=[False, True])

          country  year  population continent  life_exp       gdp_cap
1705    Sri Lanka  2022   130000000      Asia    80.000    500.000000
1706    Sri Lanka  2022   130000000      Asia    80.000    500.000000
1462    Swaziland  2007     1133066    Africa    39.613   4513.480643
1042   Mozambique  2007    19951656    Africa    42.082    823.685621
1690       Zambia  2007    11746035    Africa    42.384   1271.211593
...           ...   ...         ...       ...       ...           ...
1463       Sweden  1952     7124673    Europe    71.860   8527.844662
1079  Netherlands  1952    10381988    Europe    72.130   8941.571858
683       Iceland  1952      147962    Europe    72.490   7267.688428
1139       Norway  1952     3327728    Europe    72.670  10095.421720
1703        Japan  1000     1350000      Asia    37.080    100.230000

[1708 rows x 6 columns]

In [ ]:
# df.sort_values(['country','population'], inplace=True, ascending=False)

In [ ]:
users = pd.DataFrame({"userid":[1, 2, 3], "name":["sharadh", "shahid", "khusalli"]})
users

   userid      name
0       1   sharadh
1       2    shahid
2       3  khusalli

In [ ]:
msgs = pd.DataFrame({"userid":[1, 1, 2, 4], "msg":['hmm', "acha", "theek hai", "nice"]})
msgs

   userid        msg
0       1        hmm
1       1       acha
2       2  theek hai
3       4       nice

In [ ]:
pd.concat([users, msgs])

   userid      name        msg
0       1   sharadh        NaN
1       2    shahid        NaN
2       3  khusalli        NaN
0       1       NaN        hmm
1       1       NaN       acha
2       2       NaN  theek hai
3       4       NaN       nice

In [ ]:
pd.concat([users, msgs], ignore_index=True)

   userid      name        msg
0       1   sharadh        NaN
1       2    shahid        NaN
2       3  khusalli        NaN
3       1       NaN        hmm
4       1       NaN       acha
5       2       NaN  theek hai
6       4       NaN       nice

In [ ]:
pd.concat([users, msgs], axis = 1)

   userid      name  userid        msg
0     1.0   sharadh       1        hmm
1     2.0    shahid       1       acha
2     3.0  khusalli       2  theek hai
3     NaN       NaN       4       nice

In [ ]:
users.merge(msgs, on='userid')

# pd.concat(...)
# df.merge(...)

   userid     name        msg
0       1  sharadh        hmm
1       1  sharadh       acha
2       2   shahid  theek hai

In [ ]:
users.merge(msgs, on="userid", how="outer")

   userid      name        msg
0       1   sharadh        hmm
1       1   sharadh       acha
2       2    shahid  theek hai
3       3  khusalli        NaN
4       4       NaN       nice

In [ ]:
users.merge(msgs, on="userid", how="left")

   userid      name        msg
0       1   sharadh        hmm
1       1   sharadh       acha
2       2    shahid  theek hai
3       3  khusalli        NaN

In [ ]:
users.merge(msgs, on="userid", how="right")

   userid     name        msg
0       1  sharadh        hmm
1       1  sharadh       acha
2       2   shahid  theek hai
3       4      NaN       nice

In [ ]:
users

   userid      name
0       1   sharadh
1       2    shahid
2       3  khusalli

In [ ]:
msgs

   userid        msg
0       1        hmm
1       1       acha
2       2  theek hai
3       4       nice

In [ ]:
users.rename(columns = {"userid": "id"}, inplace=True)
users

   id      name
0   1   sharadh
1   2    shahid
2   3  khusalli

In [ ]:
users.merge(msgs, left_on='id', right_on='userid')

   id     name  userid        msg
0   1  sharadh       1        hmm
1   1  sharadh       1       acha
2   2   shahid       2  theek hai

In [ ]:
df1 = pd.DataFrame({'A':[10,30], 'B':[20,40], 'C':[30, 60]})
df2 = pd.DataFrame({'A':[10,30], 'C':[30, 60]})
#df2.merge(df1, on = 'A', how = 'outer')

df1

    A   B   C
0  10  20  30
1  30  40  60

In [ ]:
df2

    A   C
0  10  30
1  30  60

In [ ]:
df2.merge(df1, on = 'A', how = 'outer')

    A  C_x   B  C_y
0  10   30  20   30
1  30   60  40   60